// Bloom Health — Direct PostgreSQL & Supabase Database Driver
require('dotenv').config();
const { Pool } = require('pg');
const { initialDishes, initialMealCombinations, initialExercises } = require('./seedData');

let pool = null;
let isPgConnected = false;

const connectionString = process.env.DATABASE_URL || process.env.POSTGRES_URL || process.env.SUPABASE_DB_URL;

if (connectionString && !connectionString.includes('[YOUR-PASSWORD]')) {
  pool = new Pool({
    connectionString,
    ssl: { rejectUnauthorized: false }
  });
} else if (process.env.PG_HOST && process.env.PG_PASSWORD && !process.env.PG_PASSWORD.includes('[YOUR-PASSWORD]')) {
  pool = new Pool({
    host: process.env.PG_HOST,
    port: parseInt(process.env.PG_PORT || '5432', 10),
    database: process.env.PG_DATABASE || 'postgres',
    user: process.env.PG_USER || 'postgres',
    password: process.env.PG_PASSWORD,
    ssl: { rejectUnauthorized: false }
  });
}

/**
 * Initialize PostgreSQL / Supabase Tables & Seed Data
 */
async function initPgDb() {
  if (!pool) return false;

  try {
    const client = await pool.connect();
    console.log('⚡ Connected directly to PostgreSQL / Supabase Database!');
    isPgConnected = true;

    // 1. Dishes Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS dishes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        description TEXT,
        prep_time_minutes INTEGER DEFAULT 15,
        calories INTEGER DEFAULT 350,
        protein_g NUMERIC DEFAULT 15.0,
        carbs_g NUMERIC DEFAULT 35.0,
        fat_g NUMERIC DEFAULT 12.0,
        folate_mcg NUMERIC DEFAULT 120.0,
        iron_mg NUMERIC DEFAULT 3.0,
        calcium_mg NUMERIC DEFAULT 100.0,
        dha_mg NUMERIC DEFAULT 0.0,
        trimester_recommendation TEXT DEFAULT 'All Trimesters',
        dietary_tags TEXT,
        image_url TEXT,
        recipe_steps JSONB DEFAULT '[]'::jsonb,
        ingredients JSONB DEFAULT '[]'::jsonb,
        is_favorite INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 2. Meal Combinations Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS meal_combinations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        subtitle TEXT,
        category TEXT DEFAULT 'Lunch',
        synergy_benefit TEXT NOT NULL,
        calories INTEGER DEFAULT 500,
        protein_g NUMERIC DEFAULT 25.0,
        folate_mcg NUMERIC DEFAULT 200.0,
        iron_mg NUMERIC DEFAULT 5.0,
        calcium_mg NUMERIC DEFAULT 200.0,
        dha_mg NUMERIC DEFAULT 0.0,
        main_dish_name TEXT,
        main_dish_id BIGINT,
        side_item_name TEXT,
        side_item_image TEXT,
        image_url TEXT,
        tags TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 3. Meal Logs Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS meal_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dish_id BIGINT,
        dish_name TEXT NOT NULL,
        category TEXT,
        calories INTEGER DEFAULT 0,
        protein_g NUMERIC DEFAULT 0.0,
        folate_mcg NUMERIC DEFAULT 0.0,
        iron_mg NUMERIC DEFAULT 0.0,
        date DATE DEFAULT CURRENT_DATE,
        logged_at TIMESTAMPTZ DEFAULT NOW(),
        notes TEXT
      );
    `);

    // 4. Daily Metrics Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS daily_metrics (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE UNIQUE NOT NULL DEFAULT CURRENT_DATE,
        steps INTEGER DEFAULT 6420,
        step_goal INTEGER DEFAULT 8000,
        water_liters NUMERIC DEFAULT 1.5,
        water_goal_liters NUMERIC DEFAULT 2.5,
        active_calories INTEGER DEFAULT 420,
        active_calories_goal INTEGER DEFAULT 500,
        active_minutes INTEGER DEFAULT 35,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 5. User Profile Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS user_profile (
        id BIGINT PRIMARY KEY DEFAULT 1,
        name TEXT DEFAULT 'Sarah Miller',
        avatar_url TEXT DEFAULT '/assets/sarah-avatar.png',
        pregnancy_week INTEGER DEFAULT 24,
        trimester INTEGER DEFAULT 2,
        due_date TEXT DEFAULT 'Nov 15, 2026',
        baby_comparison TEXT DEFAULT 'an ear of corn',
        weight_lbs NUMERIC DEFAULT 142.0,
        height TEXT DEFAULT '5'' 6"',
        age INTEGER DEFAULT 31,
        daily_insights_enabled BOOLEAN DEFAULT TRUE,
        language TEXT DEFAULT 'English',
        units TEXT DEFAULT 'Imperial',
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 6. Notifications Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS notifications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        message TEXT NOT NULL,
        category TEXT DEFAULT 'general',
        type TEXT DEFAULT 'info',
        is_read INTEGER DEFAULT 0,
        action_type TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 7. Kick Sessions Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS kick_sessions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_date DATE DEFAULT CURRENT_DATE,
        duration_seconds INTEGER DEFAULT 0,
        kick_count INTEGER NOT NULL,
        notes TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 8. Wellness Logs Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS wellness_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE UNIQUE NOT NULL DEFAULT CURRENT_DATE,
        mood TEXT,
        symptoms TEXT,
        energy_level INTEGER DEFAULT 4,
        notes TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 9. Exercises Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS exercises (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        trimester_safe TEXT DEFAULT 'All Trimesters',
        duration_minutes INTEGER DEFAULT 5,
        intensity TEXT DEFAULT 'Gentle',
        equipment TEXT DEFAULT 'Yoga Mat',
        benefits TEXT NOT NULL,
        cues TEXT NOT NULL,
        steps JSONB DEFAULT '[]'::jsonb,
        safety_tips TEXT,
        calories_burn INTEGER DEFAULT 25,
        image_url TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 10. Workout Logs Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS workout_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        exercise_id BIGINT,
        exercise_name TEXT NOT NULL,
        category TEXT,
        duration_minutes INTEGER DEFAULT 5,
        calories_burned INTEGER DEFAULT 25,
        date DATE DEFAULT CURRENT_DATE,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Check & Seed Dishes
    const dishesCheck = await client.query('SELECT COUNT(*) as count FROM dishes');
    if (parseInt(dishesCheck.rows[0].count, 10) === 0) {
      console.log('🌱 Seeding prenatal dishes into PostgreSQL...');
      for (const d of initialDishes) {
        await client.query(`
          INSERT INTO dishes (
            name, category, description, prep_time_minutes, calories,
            protein_g, carbs_g, fat_g, folate_mcg, iron_mg, calcium_mg, dha_mg,
            trimester_recommendation, dietary_tags, image_url, recipe_steps,
            ingredients, is_favorite
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
        `, [
          d.name, d.category, d.description, d.prep_time_minutes, d.calories,
          d.protein_g, d.carbs_g, d.fat_g, d.folate_mcg, d.iron_mg, d.calcium_mg, d.dha_mg,
          d.trimester_recommendation, d.dietary_tags, d.image_url,
          JSON.stringify(JSON.parse(d.recipe_steps || '[]')),
          JSON.stringify(JSON.parse(d.ingredients || '[]')),
          d.is_favorite
        ]);
      }
    }

    // Check & Seed Combinations
    const comboCheck = await client.query('SELECT COUNT(*) as count FROM meal_combinations');
    if (parseInt(comboCheck.rows[0].count, 10) === 0) {
      console.log('🌱 Seeding meal combinations into PostgreSQL...');
      for (const c of initialMealCombinations) {
        await client.query(`
          INSERT INTO meal_combinations (
            name, subtitle, category, synergy_benefit, calories, protein_g,
            folate_mcg, iron_mg, calcium_mg, dha_mg, main_dish_name, main_dish_id,
            side_item_name, side_item_image, image_url, tags
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
        `, [
          c.name, c.subtitle, c.category, c.synergy_benefit, c.calories, c.protein_g,
          c.folate_mcg, c.iron_mg, c.calcium_mg, c.dha_mg, c.main_dish_name, c.main_dish_id,
          c.side_item_name, c.side_item_image, c.image_url, c.tags
        ]);
      }
    }

    // Check & Seed Exercises
    const exCheck = await client.query('SELECT COUNT(*) as count FROM exercises');
    if (parseInt(exCheck.rows[0].count, 10) === 0) {
      console.log('🌱 Seeding exercises into PostgreSQL...');
      for (const e of initialExercises) {
        await client.query(`
          INSERT INTO exercises (
            name, category, trimester_safe, duration_minutes, intensity,
            equipment, benefits, cues, steps, safety_tips, calories_burn, image_url
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
        `, [
          e.name, e.category, e.trimester_safe, e.duration_minutes, e.intensity,
          e.equipment, e.benefits, e.cues,
          JSON.stringify(JSON.parse(e.steps || '[]')),
          e.safety_tips, e.calories_burn, e.image_url
        ]);
      }
    }

    // Ensure Profile
    await client.query(`
      INSERT INTO user_profile (id, name, pregnancy_week, trimester, due_date, baby_comparison, weight_lbs, height, age)
      VALUES (1, 'Sarah Miller', 24, 2, 'Nov 15, 2026', 'an ear of corn', 142.0, '5'' 6"', 31)
      ON CONFLICT (id) DO NOTHING;
    `);

    // Ensure Today's Metrics
    await client.query(`
      INSERT INTO daily_metrics (date, steps, step_goal, water_liters, water_goal_liters, active_calories, active_calories_goal, active_minutes)
      VALUES (CURRENT_DATE, 6420, 8000, 1.5, 2.5, 420, 500, 35)
      ON CONFLICT (date) DO NOTHING;
    `);

    client.release();
    return true;
  } catch (err) {
    console.warn('⚠️ PostgreSQL connection/initialization error:', err.message);
    isPgConnected = false;
    return false;
  }
}

module.exports = {
  pool,
  isPgConnected,
  initPgDb
};
