-- ==============================================================================
-- 🌸 BLOOM HEALTH — SUPABASE POSTGRESQL DATABASE SCHEMA & SEED DATA
-- Copy and paste this script directly into your Supabase Dashboard SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 1. Dishes Table
CREATE TABLE IF NOT EXISTS public.dishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  prep_time_minutes INTEGER DEFAULT 15,
  calories INTEGER DEFAULT 350,
  protein_g NUMERIC DEFAULT 15.0,
  carbs_g NUMERIC DEFAULT 35.0,
  fat_g NUMERIC DEFAULT 12.0,
  folate_mcg NUMERIC DEFAULT 120.0,
  iron_mg NUMERIC DEFAULT 3.0,
  calcium_mg NUMERIC DEFAULT 100.0,
  dha_mg NUMERIC DEFAULT 0.0,
  trimester_recommendation TEXT DEFAULT 'All Trimesters',
  dietary_tags TEXT,
  image_url TEXT,
  recipe_steps JSONB DEFAULT '[]'::jsonb,
  ingredients JSONB DEFAULT '[]'::jsonb,
  is_favorite INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Meal Combinations & Power Pairings Table
CREATE TABLE IF NOT EXISTS public.meal_combinations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  subtitle TEXT,
  category TEXT DEFAULT 'Lunch',
  synergy_benefit TEXT NOT NULL,
  calories INTEGER DEFAULT 500,
  protein_g NUMERIC DEFAULT 25.0,
  folate_mcg NUMERIC DEFAULT 200.0,
  iron_mg NUMERIC DEFAULT 5.0,
  calcium_mg NUMERIC DEFAULT 200.0,
  dha_mg NUMERIC DEFAULT 0.0,
  main_dish_name TEXT,
  main_dish_id BIGINT,
  side_item_name TEXT,
  side_item_image TEXT,
  image_url TEXT,
  tags TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Meal Logs Table
CREATE TABLE IF NOT EXISTS public.meal_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dish_id BIGINT REFERENCES public.dishes(id) ON DELETE SET NULL,
  dish_name TEXT NOT NULL,
  category TEXT,
  calories INTEGER DEFAULT 0,
  protein_g NUMERIC DEFAULT 0.0,
  folate_mcg NUMERIC DEFAULT 0.0,
  iron_mg NUMERIC DEFAULT 0.0,
  date DATE DEFAULT CURRENT_DATE,
  logged_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT
);

-- 4. Daily Health Metrics Table
CREATE TABLE IF NOT EXISTS public.daily_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL DEFAULT CURRENT_DATE,
  steps INTEGER DEFAULT 6420,
  step_goal INTEGER DEFAULT 8000,
  water_liters NUMERIC DEFAULT 1.5,
  water_goal_liters NUMERIC DEFAULT 2.5,
  active_calories INTEGER DEFAULT 420,
  active_calories_goal INTEGER DEFAULT 500,
  active_minutes INTEGER DEFAULT 35,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. User Profile Table
CREATE TABLE IF NOT EXISTS public.user_profile (
  id BIGINT PRIMARY KEY DEFAULT 1,
  name TEXT DEFAULT 'Sarah Miller',
  avatar_url TEXT DEFAULT '/assets/sarah-avatar.png',
  pregnancy_week INTEGER DEFAULT 24,
  trimester INTEGER DEFAULT 2,
  due_date TEXT DEFAULT 'Nov 15, 2026',
  baby_comparison TEXT DEFAULT 'an ear of corn',
  weight_lbs NUMERIC DEFAULT 142.0,
  height TEXT DEFAULT '5'' 6"',
  age INTEGER DEFAULT 31,
  daily_insights_enabled BOOLEAN DEFAULT TRUE,
  language TEXT DEFAULT 'English',
  units TEXT DEFAULT 'Imperial',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Notifications & Alerts Table
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  type TEXT DEFAULT 'info',
  is_read INTEGER DEFAULT 0,
  action_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Fetal Kick Sessions Table
CREATE TABLE IF NOT EXISTS public.kick_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_date DATE DEFAULT CURRENT_DATE,
  duration_seconds INTEGER DEFAULT 0,
  kick_count INTEGER NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Daily Wellness & Mood Check-in Table
CREATE TABLE IF NOT EXISTS public.wellness_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL DEFAULT CURRENT_DATE,
  mood TEXT,
  symptoms TEXT,
  energy_level INTEGER DEFAULT 4,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Exercises Table
CREATE TABLE IF NOT EXISTS public.exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  trimester_safe TEXT DEFAULT 'All Trimesters',
  duration_minutes INTEGER DEFAULT 5,
  intensity TEXT DEFAULT 'Gentle',
  equipment TEXT DEFAULT 'Yoga Mat',
  benefits TEXT NOT NULL,
  cues TEXT NOT NULL,
  steps JSONB DEFAULT '[]'::jsonb,
  safety_tips TEXT,
  calories_burn INTEGER DEFAULT 25,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Workout Logs Table
CREATE TABLE IF NOT EXISTS public.workout_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_id BIGINT REFERENCES public.exercises(id) ON DELETE SET NULL,
  exercise_name TEXT NOT NULL,
  category TEXT,
  duration_minutes INTEGER DEFAULT 5,
  calories_burned INTEGER DEFAULT 25,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Allow Read/Write for Authenticated/Anon
ALTER TABLE public.dishes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_combinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kick_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wellness_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write on dishes" ON public.dishes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on meal_combinations" ON public.meal_combinations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on meal_logs" ON public.meal_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on daily_metrics" ON public.daily_metrics FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on user_profile" ON public.user_profile FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on kick_sessions" ON public.kick_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on wellness_logs" ON public.wellness_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on exercises" ON public.exercises FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on workout_logs" ON public.workout_logs FOR ALL USING (true) WITH CHECK (true);

-- Initial Profile Seed
INSERT INTO public.user_profile (id, name, pregnancy_week, trimester, due_date, baby_comparison, weight_lbs, height, age)
VALUES (1, 'Sarah Miller', 24, 2, 'Nov 15, 2026', 'an ear of corn', 142.0, '5'' 6"', 31)
ON CONFLICT (id) DO NOTHING;

-- Initial Daily Metrics Seed
INSERT INTO public.daily_metrics (date, steps, step_goal, water_liters, water_goal_liters, active_calories, active_calories_goal, active_minutes)
VALUES (CURRENT_DATE, 6420, 8000, 1.5, 2.5, 420, 500, 35)
ON CONFLICT (date) DO NOTHING;
